# Generated by Django 3.1.7 on 2021-04-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('day_hours', models.PositiveIntegerField(blank=True, default=8, verbose_name='Количество рабочих часов в день')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('start', models.DateField(verbose_name='Старт')),
                ('duration', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('employee_count', models.PositiveIntegerField(verbose_name='Количество работников')),
                ('salary', models.PositiveIntegerField(verbose_name='Ставка')),
                ('parent', models.ManyToManyField(blank=True, related_name='_task_parent_+', to='app.Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
