# Generated by Django 3.1.7 on 2021-04-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_parent_+', to='app.Task'),
        ),
    ]
