# Generated by Django 3.1.7 on 2021-03-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(verbose_name='Старт'),
        ),
    ]
