# Generated by Django 3.1.7 on 2021-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210317_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='day_hours',
            field=models.PositiveIntegerField(blank=True, default=8, verbose_name='Количество рабочих часов в день'),
        ),
    ]
