# Generated by Django 3.1.7 on 2021-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210402_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent',
            new_name='parents',
        ),
    ]
